"use client";
import { use, useEffect, useState } from "react";
import { api, API_BASE } from "@/lib/api";

type Domain = {id:number;base_url:string;hostname:string;status:string;total_urls:number;new_urls:number;changed_urls:number;archived_urls:number;pending_jobs:number;failed_jobs:number;last_scan_at:string|null;scheduled_scan_enabled:boolean;scan_interval_minutes:number;next_scan_at:string|null;latest_scan:any};
type UrlRow = {id:number;original_url:string;normalized_url:string;discovery_source:string;http_status:number|null;content_type:string|null;content_length:number|null;content_hash:string|null;change_status:string;robots_allowed:boolean;discovered_at:string;last_seen_at:string;archive_status:string;archive_url:string|null};

export default function DomainDetail({params}:{params:Promise<{id:string}>}){
  const {id}=use(params); const domainId=Number(id);
  const [domain,setDomain]=useState<Domain|null>(null); const [rows,setRows]=useState<UrlRow[]>([]); const [q,setQ]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function refresh(search=q){ try{ const [d,u]=await Promise.all([api<Domain>(`/api/domains/${domainId}`),api<UrlRow[]>(`/api/domains/${domainId}/urls?q=${encodeURIComponent(search)}&limit=500`)]);setDomain(d);setRows(u);setError("");}catch(e:any){setError(e.message)} }
  useEffect(()=>{refresh("");const t=setInterval(()=>refresh(q),3000);return()=>clearInterval(t)},[domainId,q]);
  async function action(kind:"scan"|"archive", force=false){setError("");setMessage("");try{const r:any=await api(`/api/domains/${domainId}/${kind}`,{method:"POST",body:kind==="archive"?JSON.stringify({force,changed_only:!force}):undefined});setMessage(r.message+(r.created!==undefined?` ${r.created} queued, ${r.skipped} skipped, ${r.blocked_or_inaccessible} blocked/inaccessible.`:""));await refresh();}catch(e:any){setError(e.message)}}
  async function toggleSchedule(){if(!domain)return; try{const enabled=!domain.scheduled_scan_enabled; const r=await api<Domain>(`/api/domains/${domainId}/schedule`,{method:"POST",body:JSON.stringify({enabled,interval_minutes:domain.scan_interval_minutes||1440})});setDomain(r);setMessage(enabled?"Scheduled scanning enabled.":"Scheduled scanning disabled.");}catch(e:any){setError(e.message)}}
  if(!domain) return <div className="panel">Loading…</div>;
  return <>
    <section className="hero"><div><h1>{domain.hostname}</h1><p className="mono">{domain.base_url}</p><p className="small">Scheduled scan: <b>{domain.scheduled_scan_enabled?`ON every ${domain.scan_interval_minutes} min`:`OFF`}</b>{domain.next_scan_at?` • next ${new Date(domain.next_scan_at).toLocaleString()}`:""}</p></div><div className="actions"><button disabled={domain.status==="SCANNING"} onClick={()=>action("scan")}>Scan again</button><button className="primary" disabled={!domain.total_urls} onClick={()=>action("archive")}>Archive new/changed</button><button onClick={()=>action("archive",true)}>Force re-archive all</button><button onClick={toggleSchedule}>{domain.scheduled_scan_enabled?"Disable schedule":"Enable daily schedule"}</button></div></section>
    {message&&<div className="notice">{message}</div>}{error&&<div className="notice error">{error}</div>}
    <section className="grid"><div className="stat"><span>Status</span><b style={{fontSize:18}}>{domain.status}</b></div><div className="stat"><span>Discovered</span><b>{domain.total_urls}</b></div><div className="stat"><span>Changed</span><b>{domain.changed_urls}</b></div><div className="stat"><span>Archived URLs</span><b>{domain.archived_urls}</b></div><div className="stat"><span>Pending</span><b>{domain.pending_jobs}</b></div></section>
    {domain.latest_scan&&<section className="panel" style={{marginBottom:18}}><div className="sectionHead"><h2>Latest scan</h2><div className="actions"><a className="button" href={`${API_BASE}/api/domains/${domainId}/export?format=csv`}>Export CSV</a><a className="button" href={`${API_BASE}/api/domains/${domainId}/export?format=json`}>Export JSON</a></div></div><p>{domain.latest_scan.urls_found} URLs • {domain.latest_scan.new_urls_found} new • {domain.latest_scan.changed_urls_found} changed • {domain.latest_scan.pages_fetched} fetched • {domain.latest_scan.duration_ms} ms • <span className={`badge ${domain.latest_scan.status}`}>{domain.latest_scan.status}</span></p>{domain.latest_scan.error_message&&<div className="notice error">{domain.latest_scan.error_message}</div>}</section>}
    <section className="panel"><div className="sectionHead"><div><h2>URL inventory</h2><p className="small">Content fingerprints make incremental backup change-aware.</p></div><input className="search" style={{maxWidth:360}} placeholder="Search URL" value={q} onChange={e=>setQ(e.target.value)}/></div>
      <div className="tableWrap"><table><thead><tr><th>URL</th><th>Change</th><th>Source</th><th>HTTP</th><th>Size</th><th>Archive</th><th>Proof</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.normalized_url}<div className="muted small">SHA-256: {r.content_hash?r.content_hash.slice(0,16)+"…":"—"}{!r.robots_allowed?" • robots blocked":""}</div></td><td><span className={`badge ${r.change_status}`}>{r.change_status}</span></td><td>{r.discovery_source}</td><td>{r.http_status??"—"}</td><td>{r.content_length!=null?`${Math.round(r.content_length/1024)} KB`:"—"}</td><td><span className={`badge ${r.archive_status}`}>{r.archive_status}</span></td><td>{r.archive_url?<a className="link" href={r.archive_url} target="_blank">Open archive</a>:"—"}</td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">No URLs found.</div>}</div>
    </section>
  </>;
}
